### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [lexicalunit/linter-just-say-no#3]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by lexicalunit** [comment]
Thanks this is awesome! :+1:

**Comment by lexicalunit** [comment]
Fixed in 1e6bc5cc423897df769a290d11858d31e2ce8f19!
