### ISSUE TITLE
Update CSS selector for linter gutter element

### ISSUE THREAD

**Issue by steelbrain** [lexicalunit/linter-just-say-no#5]
`.icon-right::before` css selector will be replaced by `.linter-gutter` of the new linter gutter element.

For more details: https://github.com/atom-community/linter/issues/906

**Comment by lexicalunit** [comment]
Ty for the heads up!

**Comment by lexicalunit** [comment]
Fixed in [v0.5.0](https://github.com/lexicalunit/linter-just-say-no/releases/tag/v0.5.0)!
