### ISSUE TITLE
Don't override Array.prototype

### ISSUE THREAD

**Issue by jerone** [lexicalunit/linter-just-say-no#7]
Please don't override the `Array.prototype` with [custom functions](https://github.com/lexicalunit/linter-just-say-no/blob/d7c97520658cd78c3d581cf38785d36d9e30457d/lib/linter-just-say-no-provider.coffee#L1). This causes issues with [other](https://github.com/Zren/atom-open-recent/issues/16) packages. Or at least use the [`enumerable` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties).

**Comment by lexicalunit** [comment]
My apologies. I legitimately thought this was idiomatic coffeescript/javascript. Resolved in 6d50ce6f91d4349c8df3cd43f25489337dcc3dbb, released in v0.6.1.

**Comment by jerone** [comment]
Packages don't execute in their own sandbox, they all share all prototypes. Thanks for solving this issue!
