### ISSUE TITLE
Deprecated selector in `linter-just-say-no/styles/linter-just-say-no.less`

### ISSUE THREAD

**Issue by molovo** [lexicalunit/linter-just-say-no#9]
In `linter-just-say-no/styles/linter-just-say-no.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.info:not(.line-number),
.linter-highlight.info:not(.line-number)` => `atom-text-editor.editor .linter-highlight.syntax--info:not(.line-number),
.linter-highlight.info:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.info .linter-gutter,
.linter-highlight.info .linter-gutter` => `atom-text-editor.editor .linter-highlight.syntax--info .linter-gutter,
.linter-highlight.info .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.info .region,
.linter-highlight.info .region` => `atom-text-editor.editor .linter-highlight.syntax--info .region,
.linter-highlight.info .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lexicalunit** [comment]
Thanks!

**Comment by lexicalunit** [comment]
Resolved.
